/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calendar.naora.recipe;

import java.awt.Component;
import javax.swing.AbstractCellEditor;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;

/**
 *
 * @author Nao
 */
public class RecipeDialog extends javax.swing.JDialog {

    private Recipe recipe;
    private TagsModel tagsModel;
    private IngrediantsModel ingrediantsModel;

    
    private class SpinnerCellEditor extends AbstractCellEditor implements TableCellEditor {
        
        private final JSpinner component;

        public SpinnerCellEditor() {
            component = new JSpinner(new SpinnerNumberModel(0.0, 0.0, 999.9, 0.5));
        }

        @Override
        public Object getCellEditorValue() {
            return component.getValue();
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) { 
            component.setValue(value);
            return component;
        }
        
    }
    
    /**
     * Creates new form RecipeDialog
     *
     * @param parent
     * @param modal
     */
    public RecipeDialog(java.awt.Frame parent, boolean modal) {
        this(parent, modal, new Recipe());
    }

    public RecipeDialog(java.awt.Frame parent, boolean modal, Recipe r) {
        super(parent, modal);
        recipe = r;
        tagsModel = new TagsModel(recipe.getTags());
        ingrediantsModel = new IngrediantsModel(recipe.getIngrediants());
        initComponents();
        initCell();
    }

    private void initCell() {
        TableColumn quantityColumn = ingrediants.getColumnModel().getColumn(1);
        TableColumn typeColumn = ingrediants.getColumnModel().getColumn(2);

        quantityColumn.setCellEditor(new SpinnerCellEditor());

        JComboBox<Ingrediant.Type> combo = new JComboBox<>();
        for (Ingrediant.Type value : Ingrediant.Type.values()) {
            combo.addItem(value);
        }
        typeColumn.setCellEditor(new DefaultCellEditor(combo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        name = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextPane();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tags = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        ingrediants = new javax.swing.JTable();
        addTag = new javax.swing.JButton();
        deleteTags = new javax.swing.JButton();
        addIngrediant = new javax.swing.JButton();
        deleteIngrediants = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(565, 397));

        name.setText(recipe.getName());

        description.setText(recipe.getDescription());
        jScrollPane3.setViewportView(description);

        ok.setText("Appliquer");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        cancel.setText("Annuler");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        tags.setModel(tagsModel);
        tags.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tags.setShowHorizontalLines(false);
        tags.setShowVerticalLines(false);
        jScrollPane5.setViewportView(tags);

        ingrediants.setModel(ingrediantsModel);
        ingrediants.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane6.setViewportView(ingrediants);

        addTag.setText("+");
        addTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTagActionPerformed(evt);
            }
        });

        deleteTags.setText("-");
        deleteTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTagsActionPerformed(evt);
            }
        });

        addIngrediant.setText("+");
        addIngrediant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIngrediantActionPerformed(evt);
            }
        });

        deleteIngrediants.setText("-");
        deleteIngrediants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteIngrediantsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ok))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteIngrediants)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addIngrediant)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(deleteTags)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addTag)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addIngrediant)
                        .addComponent(deleteIngrediants))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addTag)
                        .addComponent(deleteTags)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        recipe.setTags(tagsModel.getTags());
        recipe.setIngrediants(ingrediantsModel.getIngrediants());
        recipe.setName(name.getText());
        recipe.setDescription(description.getText());
        setVisible(false);
    }//GEN-LAST:event_okActionPerformed

    private void deleteTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTagsActionPerformed
        tagsModel.delete(tags.getSelectedRow());
    }//GEN-LAST:event_deleteTagsActionPerformed

    private void deleteIngrediantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteIngrediantsActionPerformed
        ingrediantsModel.delete(ingrediants.getSelectedRow());
    }//GEN-LAST:event_deleteIngrediantsActionPerformed

    private void addTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTagActionPerformed
        tagsModel.addRow();
    }//GEN-LAST:event_addTagActionPerformed

    private void addIngrediantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIngrediantActionPerformed
        ingrediantsModel.addRow();
    }//GEN-LAST:event_addIngrediantActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addIngrediant;
    private javax.swing.JButton addTag;
    private javax.swing.JButton cancel;
    private javax.swing.JButton deleteIngrediants;
    private javax.swing.JButton deleteTags;
    private javax.swing.JTextPane description;
    private javax.swing.JTable ingrediants;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JButton ok;
    private javax.swing.JTable tags;
    // End of variables declaration//GEN-END:variables
}
